apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planner
  template:
    metadata:
      labels:
        app: planner
    spec:
      containers:
        - name: planner
          image: mustafais/worker
          ports:
            - containerPort: 1337
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: 500m
              memory: 1Gi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---

apiVersion: v1
kind: Service
metadata:
  name: planner-service
spec:
  selector:
    app: planner
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: LoadBalancer
