apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mult-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-mult
  template:
    metadata:
      labels:
        app: worker-mult
    spec:
      containers:
        - name: worker
          image: mustafais/worker
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: PLANNER
              value: 'http://planner-service.default.svc.cluster.local:8080'
            - name: PORT
              value: '3000'
            - name: MULT
              value: 'true'
            - name: ADD
              value: 'false'
            - name: ADDRESS
              value: 'http://worker-mult-service.default.svc.cluster.local:1337'

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: worker-mult-service
spec:
  selector:
    app: worker-mult
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-add-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-add
  template:
    metadata:
      labels:
        app: worker-add
    spec:
      containers:
        - name: worker
          image: mustafais/worker
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: PLANNER
              value: 'http://planner-service.default.svc.cluster.local:8080'
            - name: PORT
              value: '3000'
            - name: MULT
              value: 'false'
            - name: ADD
              value: 'true'
            - name: ADDRESS
              value: 'http://worker-add-service.default.svc.cluster.local:1337'

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: worker-add-service
spec:
  selector:
    app: worker-add
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-general-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-general
  template:
    metadata:
      labels:
        app: worker-general
    spec:
      containers:
        - name: worker
          image: mustafais/worker
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: PLANNER
              value: 'http://planner-service.default.svc.cluster.local:8080'
            - name: PORT
              value: '3000'
            - name: MULT
              value: 'true'
            - name: ADD
              value: 'true'
            - name: ADDRESS
              value: 'http://worker-general-service.default.svc.cluster.local:1337'

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: worker-general-service
spec:
  selector:
    app: worker-general
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 3000
  type: LoadBalancer