apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: mustafais/worker
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: PLANNER
              value: 'http://planner-service.default.svc.cluster.local:8080'
            - name: PORT
              value: '3000'
            - name: MULT
              value: 'true'
            - name: ADD
              value: 'true'
            - name: ADDRESS
              value: 'http://worker-service.default.svc.cluster.local:1337'

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---

apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 3000
  type: LoadBalancer
